# The URL the site will be built for
base_url = "https://mukul-mehta.in"
title = "Mukul Mehta"
lang = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
theme = "sam"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

check_external_links = "true"

taxonomies = [
    {name = "tags", rss = true}
]
generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "charcoal"

[extra]
# Put all your custom variables here
show_word_count = true
show_reading_time = true

date_format = "%A %e %b, %Y"

home = "home"

sam_menu = [
    { text = "about", link = "/about" },
    { text = "posts", link = "/posts" },
    { text = "t.i.l.", link = "/til" },
    {text = "resume", link="/Mukul_Mehta-Resume.pdf"}
]

sam_bottom_menu = true

[extra.favicon]
favicon_16x16 = "/favicons/favicon-16x16.png"
favicon_32x32 = "/favicons/favicon-32x32.png"
apple_touch_icon = "/favicons/apple-touch-icon.png"
safari_pinned_tab = "/favicons/safari-pinned-tab.svg"
webmanifest = "/favicons/site.webmanifest"

[extra.youtube]
video_id = "7dUxTZMPWgA"

[extra.social]
mail = "mailto:hello@mukul-mehta.in"
twitter = "https://twitter.com/mukulmehta_"
github = "https://github.com/mukul-mehta"
facebook = "https://facebook.com/mukul.amehta"
rss_feed = "https://mukul-mehta.in/atom.xml"
